* Red-Portal's Emacs init.el
  Red-Portal's personal emacs configurations. Free, open to everyone.
  
** Install
   #+begin_src shell
git clone --recursive https://github.com/Red-Portal/.emacs.d ~/
cd ~/.emacs.d
emacs -setup
   #+end_src 
   
   Certain emacs packages are supposed to run a initial command at first startup.
   This is why ~-setup~ should be run an first startup.
   
   By the help of ~use-package~ most packages should be automatically installed.
   Naturally, internet connection is required at first startup.
   
** Supported Platforms
   Fully tested only on emacs25 and arch linux.
   All platforms supporting emacs25 are supposed to be partially supported.

   The most important package for C++ which is ~[[https://github.com/Andersbakken/rtags][rtags]]~ is not yet supported on Windows.
   Thus ~rtags~ is disabled on Windows by default.
   ~[[https://github.com/Sarcasm/irony-mode][irony]]~ is alternatively enabled for Windows (not tested).

** Contribution
*** Bugs
    Please feel free to contact me ( msca8h@naver.com ) Any time. 
    Any bugs, improvement suggestions, please fill an issue. 
    
*** Pull Requests
    Pull Requests for improvements are welcome. 
    However please state details, rationale for your request.

** LICENSE

    Red-Portal/.emacs.d Red-Portal's personal emacs settings. 
    Copyright (C) 2017 Red-Portal 

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
