* Red-Portal's Emacs init.el
  Red-Portal's personal emacs configurations. Free, open to everyone.<br />
  
** Install
   #+begin_src shell
git clone --recursive https://github.com/Red-Portal/.emacs.d ~/
cd ~/.emacs.d
emacs -setup
   #+end_src 
   
   Certain emacs packages are supposed to run a initial command at first startup. <br />
   This is why ~-setup~ should be run an first startup.<br />
   
   By the help of ~use-package~ most packages should be automatically installed.<br />
   Naturally, internet connection is required at first startup.<br />
   
   In order to properly use org-mode, You should run the commands below<br />
   
   #+begin_src shell
cd ./github/org-mode
make autoloads
   #+end_src 
   
   This will ensure org-mode is the newest avaiable.<br />
   The Emacs default org-mode is sometimes outdated and causes problems.<br />

** Supported Platforms
   Fully tested only on emacs25 and arch linux.<br />
   All platforms supporting emacs25 are supposed to be partially supported.<br />

   The most important package for C++ which is ~[[https://github.com/Andersbakken/rtags][rtags]]~ is not yet supported on Windows.<br />
   Thus ~rtags~ is disabled on Windows by default.<br />
   ~[[https://github.com/Sarcasm/irony-mode][irony]]~ is alternatively enabled for Windows (not tested).<br />

** Contribution
*** Bugs
    Please feel free to contact me ( msca8h@naver.com ) Any time. <br />
    Any bugs, improvement suggestions, please fill an issue. <br />
    
*** Pull Requests
    Pull Requests for improvements are welcome. <br />
    However please state details, rationale for your request.<br />

** LICENSE

    Red-Portal/.emacs.d Red-Portal's personal emacs settings. <br />
    Copyright (C) 2017 Red-Portal <br />

    This program is free software: you can redistribute it and/or modify<br />
    it under the terms of the GNU General Public License as published by<br />
    the Free Software Foundation, either version 3 of the License, or<br />
    (at your option) any later version.<br />

    This program is distributed in the hope that it will be useful,<br />
    but WITHOUT ANY WARRANTY; without even the implied warranty of<br />
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the<br />
    GNU General Public License for more details.<br />

    You should have received a copy of the GNU General Public License<br />
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
